"""Install the Claude assets (skills + slash commands) bundled with this package.

The assets live under ``claude_assets/`` next to this module and are copied into a
``.claude`` directory — either the user's global ``~/.claude`` (via the
``generate-project install-skills`` command) or a specific project's ``.claude``
(via ``generate --install-skills``). The layout under ``claude_assets`` mirrors the
``.claude`` layout, so installing is a straight copy of ``skills/`` and ``commands/``.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import (
    Iterator,
    List,
    Optional,
    Tuple,
)

CLAUDE_ASSETS_DIRNAME = "claude_assets"
# Top-level asset folders mirrored verbatim into the destination .claude directory.
ASSET_SUBDIRS = ("skills", "commands")
# Single source of truth for which files to install. Auto-generated from the asset tree
# (see write_manifest) and read by every consumer: the install helper below, both
# templates' scripts/install_claude_skills.py, and the test suite. Lives at the top of
# claude_assets/ (not under ASSET_SUBDIRS) so it is never itself installed into .claude.
MANIFEST_NAME = "asset_manifest.txt"
MANIFEST_HEADER = "# Auto-generated by `python -m generate_project.skills --write-manifest`. Do not edit."


def claude_assets_dir() -> Path:
    """Return the path to the Claude assets bundled with the installed package."""
    return Path(__file__).parent / CLAUDE_ASSETS_DIRNAME


def _iter_assets(assets_dir: Path) -> Iterator[Tuple[Path, Path]]:
    """Yield ``(relative_path, source_file)`` for every file to install."""
    for subdir in ASSET_SUBDIRS:
        base = assets_dir / subdir
        if not base.is_dir():
            continue
        for src in sorted(base.rglob("*")):
            if src.is_file() and not any(part.startswith(".") for part in src.parts):
                yield src.relative_to(assets_dir), src


def manifest_path(assets_dir: Optional[Path] = None) -> Path:
    """Return the path to the asset manifest within ``assets_dir`` (defaults to bundled)."""
    return (assets_dir or claude_assets_dir()) / MANIFEST_NAME


def generate_manifest_lines(assets_dir: Optional[Path] = None) -> List[str]:
    """Return the sorted POSIX relative paths of every bundled asset file (the truth)."""
    assets_dir = assets_dir or claude_assets_dir()
    return sorted(rel.as_posix() for rel, _ in _iter_assets(assets_dir))


def parse_manifest(text: str) -> List[str]:
    """Parse manifest text into relative paths, skipping blank lines and ``#`` comments."""
    return [line.strip() for line in text.splitlines() if line.strip() and not line.lstrip().startswith("#")]


def read_manifest(assets_dir: Optional[Path] = None) -> List[str]:
    """Return the asset relative paths recorded in the manifest file."""
    return parse_manifest(manifest_path(assets_dir).read_text())


def write_manifest(assets_dir: Optional[Path] = None) -> Path:
    """(Re)generate the asset manifest from the asset tree and return its path."""
    path = manifest_path(assets_dir)
    lines = [MANIFEST_HEADER, *generate_manifest_lines(assets_dir)]
    path.write_text("\n".join(lines) + "\n")
    return path


def install_claude_skills(
    dest: Path,
    *,
    force: bool = False,
    dry_run: bool = False,
    assets_dir: Optional[Path] = None,
) -> Tuple[List[Path], List[Path]]:
    """Copy the bundled ``skills/`` and ``commands/`` into ``dest`` (a ``.claude`` dir).

    Args:
        dest: The ``.claude`` directory to install into (created if needed).
        force: Overwrite files that already exist (otherwise they are skipped).
        dry_run: Compute what would be installed without writing anything.
        assets_dir: Source assets directory; defaults to the package's bundled assets.

    Returns:
        A ``(installed, skipped)`` tuple of destination paths.
    """
    assets_dir = assets_dir or claude_assets_dir()
    installed: List[Path] = []
    skipped: List[Path] = []
    for rel in read_manifest(assets_dir):
        src = assets_dir / rel
        target = dest / rel
        if target.exists() and not force:
            skipped.append(target)
            continue
        installed.append(target)
        if dry_run:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, target)
    return installed, skipped


def main(argv: Optional[List[str]] = None) -> int:
    """CLI for regenerating the asset manifest (used by ``make manifest``/format/pre-commit)."""
    parser = argparse.ArgumentParser(description="Maintain the bundled Claude asset manifest.")
    parser.add_argument(
        "--write-manifest",
        action="store_true",
        help="Regenerate claude_assets/asset_manifest.txt from the asset tree.",
    )
    args = parser.parse_args(argv)
    if args.write_manifest:
        path = write_manifest()
        print(f"Wrote {path}")
        return 0
    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
